// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82a61Jgfko9wAKk9IXAT5qHqZGAR5QqY',
    appId: '1:319947653691:web:a8511b0ae8ec43b76f521e',
    messagingSenderId: '319947653691',
    projectId: 'bykea-skardu',
    authDomain: 'bykea-skardu.firebaseapp.com',
    storageBucket: 'bykea-skardu.firebasestorage.app',
    measurementId: 'G-4G8H0VLDTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1ztY2aMeOh_uy_WRFzIfmYaJtJEcI88',
    appId: '1:319947653691:android:77b5a9a986c58f7a6f521e',
    messagingSenderId: '319947653691',
    projectId: 'bykea-skardu',
    storageBucket: 'bykea-skardu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvzy_ZT6bo6mSNp21h7r87o14AtDhcXUY',
    appId: '1:319947653691:ios:e3941918d21efd4c6f521e',
    messagingSenderId: '319947653691',
    projectId: 'bykea-skardu',
    storageBucket: 'bykea-skardu.firebasestorage.app',
    iosBundleId: 'com.example.bykeaSkardu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvzy_ZT6bo6mSNp21h7r87o14AtDhcXUY',
    appId: '1:319947653691:ios:e3941918d21efd4c6f521e',
    messagingSenderId: '319947653691',
    projectId: 'bykea-skardu',
    storageBucket: 'bykea-skardu.firebasestorage.app',
    iosBundleId: 'com.example.bykeaSkardu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD82a61Jgfko9wAKk9IXAT5qHqZGAR5QqY',
    appId: '1:319947653691:web:a85ba779f679e3566f521e',
    messagingSenderId: '319947653691',
    projectId: 'bykea-skardu',
    authDomain: 'bykea-skardu.firebaseapp.com',
    storageBucket: 'bykea-skardu.firebasestorage.app',
    measurementId: 'G-2BB5602LPC',
  );
}
